import heroImage from '@assets/images/Gemini_Generated_Image_l47jmll47jmll47j.png'
import productImage from '@assets/images/Gemini_Generated_Image_rfl2g8rfl2g8rfl2.png'
import heroVideo from '@assets/videos/Shri_Shyam_Enterprises_bike_batt…_202606151356.mp4'

export { heroImage, productImage, heroVideo }

export const categories = [
  {
    id: 'bike-batteries',
    name: 'Bike Batteries',
    slug: 'bike-batteries',
    description: 'High-performance batteries for motorcycles and bikes.',
    image: productImage,
    productCount: 12,
  },
  {
    id: 'scooter-batteries',
    name: 'Scooter Batteries',
    slug: 'scooter-batteries',
    description: 'Reliable power for scooters and mopeds.',
    image: heroImage,
    productCount: 8,
  },
  {
    id: 'inverter-batteries',
    name: 'Inverter Batteries',
    slug: 'inverter-batteries',
    description: 'Long backup inverter batteries for home and office.',
    image: productImage,
    productCount: 6,
  },
  {
    id: 'auto-batteries',
    name: 'Auto Batteries',
    slug: 'auto-batteries',
    description: 'Heavy-duty batteries for cars and commercial vehicles.',
    image: heroImage,
    productCount: 10,
  },
  {
    id: 'small-utility-batteries',
    name: 'Small Utility Batteries',
    slug: 'small-utility-batteries',
    description: 'Compact batteries for UPS, generators, and small appliances.',
    image: productImage,
    productCount: 5,
  },
]

export const products = [
  {
    id: 'prod-001',
    name: 'SS Power Bike Pro 12V 5Ah',
    slug: 'ss-power-bike-pro-12v-5ah',
    categoryId: 'bike-batteries',
    price: 1299,
    originalPrice: 1599,
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    stockCount: 45,
    isFeatured: true,
    isBestSelling: true,
    isNew: false,
    images: [productImage, heroImage, productImage],
    capacity: '5 Ah',
    voltage: '12V',
    warranty: '24 Months',
    description:
      'Premium bike battery with advanced calcium alloy plates for maintenance-free performance. Ideal for 100cc to 150cc motorcycles.',
    specifications: {
      type: 'Maintenance Free',
      dimensions: '122 x 60 x 129 mm',
      weight: '1.8 kg',
      terminal: 'Top Post',
      cranking: '85 CCA',
    },
    createdAt: '2025-11-01',
  },
  {
    id: 'prod-002',
    name: 'SS Thunder Bike 12V 7Ah',
    slug: 'ss-thunder-bike-12v-7ah',
    categoryId: 'bike-batteries',
    price: 1699,
    originalPrice: 1999,
    rating: 4.7,
    reviewCount: 98,
    inStock: true,
    stockCount: 32,
    isFeatured: true,
    isBestSelling: true,
    isNew: true,
    images: [heroImage, productImage],
    capacity: '7 Ah',
    voltage: '12V',
    warranty: '24 Months',
    description:
      'High cranking power bike battery designed for heavy-duty usage and extreme weather conditions.',
    specifications: {
      type: 'Maintenance Free',
      dimensions: '151 x 65 x 94 mm',
      weight: '2.1 kg',
      terminal: 'Top Post',
      cranking: '110 CCA',
    },
    createdAt: '2026-01-15',
  },
  {
    id: 'prod-003',
    name: 'SS Scooter Max 12V 5Ah',
    slug: 'ss-scooter-max-12v-5ah',
    categoryId: 'scooter-batteries',
    price: 1199,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 76,
    inStock: true,
    stockCount: 28,
    isFeatured: true,
    isBestSelling: false,
    isNew: false,
    images: [productImage, heroImage],
    capacity: '5 Ah',
    voltage: '12V',
    warranty: '18 Months',
    description:
      'Compact scooter battery with excellent vibration resistance and fast recharge.',
    specifications: {
      type: 'Maintenance Free',
      dimensions: '122 x 60 x 129 mm',
      weight: '1.7 kg',
      terminal: 'Side Post',
      cranking: '80 CCA',
    },
    createdAt: '2025-09-20',
  },
  {
    id: 'prod-004',
    name: 'SS Inverter Plus 150Ah',
    slug: 'ss-inverter-plus-150ah',
    categoryId: 'inverter-batteries',
    price: 12499,
    originalPrice: 13999,
    rating: 4.9,
    reviewCount: 54,
    inStock: true,
    stockCount: 15,
    isFeatured: true,
    isBestSelling: true,
    isNew: false,
    images: [heroImage, productImage],
    capacity: '150 Ah',
    voltage: '12V',
    warranty: '36 Months',
    description:
      'Tubular inverter battery with deep cycle technology for extended backup during power cuts.',
    specifications: {
      type: 'Tubular',
      dimensions: '508 x 222 x 240 mm',
      weight: '48 kg',
      terminal: 'Dual',
      backup: '8-10 Hours',
    },
    createdAt: '2025-08-10',
  },
  {
    id: 'prod-005',
    name: 'SS Auto Drive 65Ah',
    slug: 'ss-auto-drive-65ah',
    categoryId: 'auto-batteries',
    price: 6499,
    originalPrice: 7299,
    rating: 4.5,
    reviewCount: 41,
    inStock: false,
    stockCount: 0,
    isFeatured: true,
    isBestSelling: false,
    isNew: true,
    images: [productImage, heroImage],
    capacity: '65 Ah',
    voltage: '12V',
    warranty: '24 Months',
    description:
      'Automotive battery for sedans and hatchbacks with superior cold cranking performance.',
    specifications: {
      type: 'Flooded',
      dimensions: '242 x 175 x 190 mm',
      weight: '16 kg',
      terminal: 'Top Post',
      cranking: '580 CCA',
    },
    createdAt: '2026-02-01',
  },
  {
    id: 'prod-006',
    name: 'SS Utility Mini 7Ah',
    slug: 'ss-utility-mini-7ah',
    categoryId: 'small-utility-batteries',
    price: 899,
    originalPrice: 1099,
    rating: 4.4,
    reviewCount: 33,
    inStock: true,
    stockCount: 60,
    isFeatured: false,
    isBestSelling: true,
    isNew: false,
    images: [heroImage, productImage],
    capacity: '7 Ah',
    voltage: '12V',
    warranty: '12 Months',
    description:
      'Versatile small battery for UPS, alarm systems, and portable equipment.',
    specifications: {
      type: 'Sealed Lead Acid',
      dimensions: '151 x 65 x 94 mm',
      weight: '2.0 kg',
      terminal: 'F1/F2',
      cranking: 'N/A',
    },
    createdAt: '2025-07-05',
  },
  {
    id: 'prod-007',
    name: 'SS Bike Elite 12V 9Ah',
    slug: 'ss-bike-elite-12v-9ah',
    categoryId: 'bike-batteries',
    price: 2199,
    originalPrice: 2499,
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    stockCount: 22,
    isFeatured: false,
    isBestSelling: true,
    isNew: true,
    images: [productImage, heroImage],
    capacity: '9 Ah',
    voltage: '12V',
    warranty: '30 Months',
    description:
      'Premium bike battery for 150cc+ motorcycles with enhanced plate design.',
    specifications: {
      type: 'Maintenance Free',
      dimensions: '151 x 87 x 105 mm',
      weight: '2.5 kg',
      terminal: 'Top Post',
      cranking: '130 CCA',
    },
    createdAt: '2026-03-01',
  },
  {
    id: 'prod-008',
    name: 'SS Scooter Pro 12V 7Ah',
    slug: 'ss-scooter-pro-12v-7ah',
    categoryId: 'scooter-batteries',
    price: 1499,
    originalPrice: 1699,
    rating: 4.6,
    reviewCount: 52,
    inStock: true,
    stockCount: 38,
    isFeatured: false,
    isBestSelling: false,
    isNew: false,
    images: [heroImage, productImage],
    capacity: '7 Ah',
    voltage: '12V',
    warranty: '18 Months',
    description: 'High-performance scooter battery with spill-proof design.',
    specifications: {
      type: 'Maintenance Free',
      dimensions: '151 x 65 x 94 mm',
      weight: '2.0 kg',
      terminal: 'Side Post',
      cranking: '95 CCA',
    },
    createdAt: '2025-10-12',
  },
  {
    id: 'prod-009',
    name: 'SS Inverter Home 120Ah',
    slug: 'ss-inverter-home-120ah',
    categoryId: 'inverter-batteries',
    price: 9999,
    originalPrice: 11499,
    rating: 4.7,
    reviewCount: 38,
    inStock: true,
    stockCount: 20,
    isFeatured: false,
    isBestSelling: true,
    isNew: false,
    images: [productImage, heroImage],
    capacity: '120 Ah',
    voltage: '12V',
    warranty: '36 Months',
    description: 'Reliable home inverter battery with low self-discharge rate.',
    specifications: {
      type: 'Tubular',
      dimensions: '508 x 222 x 240 mm',
      weight: '42 kg',
      terminal: 'Dual',
      backup: '6-8 Hours',
    },
    createdAt: '2025-06-18',
  },
  {
    id: 'prod-010',
    name: 'SS Auto Heavy 80Ah',
    slug: 'ss-auto-heavy-80ah',
    categoryId: 'auto-batteries',
    price: 8499,
    originalPrice: 9499,
    rating: 4.5,
    reviewCount: 29,
    inStock: true,
    stockCount: 12,
    isFeatured: false,
    isBestSelling: false,
    isNew: true,
    images: [heroImage, productImage],
    capacity: '80 Ah',
    voltage: '12V',
    warranty: '24 Months',
    description: 'Heavy-duty auto battery for SUVs and commercial vehicles.',
    specifications: {
      type: 'Flooded',
      dimensions: '315 x 175 x 190 mm',
      weight: '20 kg',
      terminal: 'Top Post',
      cranking: '720 CCA',
    },
    createdAt: '2026-01-20',
  },
]

export const testimonials = [
  {
    id: 'test-1',
    name: 'Rajesh Kumar',
    role: 'Bike Owner, Delhi',
    rating: 5,
    text: 'SS Power Bike Pro has been running flawlessly for 18 months. Best battery I have used for my Pulsar.',
    avatar: 'RK',
  },
  {
    id: 'test-2',
    name: 'Priya Sharma',
    role: 'Retail Shop Owner',
    rating: 5,
    text: 'We stock Shri Shyam batteries exclusively. Our customers love the warranty support and fast delivery.',
    avatar: 'PS',
  },
  {
    id: 'test-3',
    name: 'Amit Patel',
    role: 'Battery Dealer, Gujarat',
    rating: 5,
    text: 'Excellent dealer margins and consistent quality. The inverter range sells exceptionally well.',
    avatar: 'AP',
  },
  {
    id: 'test-4',
    name: 'Suresh Reddy',
    role: 'Auto Parts Store',
    rating: 4,
    text: 'Professional team and reliable products. Auto battery range is competitive and well-packaged.',
    avatar: 'SR',
  },
]

export const productReviews = {
  'prod-001': [
    {
      id: 'rev-1',
      author: 'Vikram S.',
      rating: 5,
      date: '2026-01-10',
      comment: 'Excellent cranking power even in cold mornings.',
    },
    {
      id: 'rev-2',
      author: 'Anil M.',
      rating: 4,
      date: '2025-12-05',
      comment: 'Good value for money. Installation was easy.',
    },
  ],
  'prod-002': [
    {
      id: 'rev-3',
      author: 'Deepak R.',
      rating: 5,
      date: '2026-02-20',
      comment: 'Perfect for my Royal Enfield. Highly recommended.',
    },
  ],
  'prod-004': [
    {
      id: 'rev-4',
      author: 'Meena K.',
      rating: 5,
      date: '2025-11-15',
      comment: 'Backup lasts 9+ hours with 3 fans and 2 lights.',
    },
  ],
}
